###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

#smartdocker-memcached:
#  image: phpdockerio/memcached:latest
#  container_name: smartdocker-memcached
#  volumes:
#        - ../memcached:/var/lib/redis

smartdocker-mailhog:
  image: phpdockerio/mailhog:latest
  container_name: smartdocker-mailhog
  ports:
    - "8081:8025"

#smartdocker-redis:
#  image: phpdockerio/redis:latest
#  container_name: smartdocker-redis
#  volumes:
#      - ../redis:/var/lib/redis

smartdocker-mysql:
  image: mysql:5.7
  container_name: smartdocker-mysql
  ports:
     - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=P@ssw0rd
    - MYSQL_DATABASE=smart-db
    - MYSQL_USER=adminuser
    - MYSQL_PASSWORD=P@ssw0rd
  volumes:
    - ../mysql:/var/lib/mysql

#smartdocker-postgres:
#  image: postgres:9.6
#  container_name: smartdocker-postgres
#  environment:
#    - POSTGRES_USER=adminuser
#    - POSTGRES_PASSWORD=P@ssw0rd
#    - POSTGRES_DB=P@ssw0rd

smartdocker-webserver:
  image: phpdockerio/nginx:latest
  container_name: smartdocker-webserver
  volumes:
      - ../website:/var/www/smartdocker
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/sites-include:/etc/nginx/conf.d/sites-include/
  ports:
      - "8080:80"
  links:
      - smartdocker-php7-fpm
      - smartdocker-php56-fpm

smartdocker-php7-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile7
  container_name: smartdocker-php7-fpm
  volumes:
      - ../website:/var/www/smartdocker
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  ports:
      - "9001:9000"
  links:
      - smartdocker-mysql
#      - smartdocker-memcached
#      - smartdocker-redis
      - smartdocker-mailhog

smartdocker-php56-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile56
  container_name: smartdocker-php56-fpm
  volumes:
      - ../website:/var/www/smartdocker
      - ./php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
  ports:
      - "9002:9000"
  links:
      - smartdocker-mysql
#      - smartdocker-memcached
#      - smartdocker-redis
      - smartdocker-mailhog
